apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-teste
  name: nginx-teste
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0
  replicas: 10
  selector:
    matchLabels:
      app: nginx-teste
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-teste
    spec:
      containers:
      - image: httpd
        name: nginx
        resources:
          requests:
            cpu: 100m
            memory: 512M
          limits:
            cpu: 1  
            memory: 8G
